########################################################################
# Overwrite environment variables for Local
########################################################################

lowCarbPower-portal:
  image: hvashistha54/lowCarbPower-portal:latest
  mem_limit: 1000000000
  ports:
    - 9000:9000
  environment:
    spring.profiles.active: local
    server.port: 9000
    spring.datasource.url: jdbc:mysql://localhost:3306/RefactorCustomerRadar
    spring.datasource.username: root
    spring.datasource.password: root1234
    